index:
    path: /
    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\DefaultController::login


##todoApp
ToDoIndex:
    path: /todoapp/
    controller: App\Controller\ToDoController::index
saveToDo:
    path: /todoapp/saveToDo
    controller: App\Controller\ToDoController::saveToDo
deleteToDo:
    path: /todoapp/deleteToDo
    controller: App\Controller\ToDoController::deleteToDo
changeIsDoneToDo:
    path: /todoapp/changeIsDoneToDo
    controller: App\Controller\ToDoController::changeIsDoneToDo